# Generated by Django 5.0.1 on 2024-02-08 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
